name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install flake8
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t veryfastapi .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop old container
        run: |
          docker stop veryfastapi || true
          docker rm veryfastapi || true
      - name: Run new container
        run: |
          docker run -d --name veryfastapi -p 5000:5000 veryfastapi
